name: Test Build

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Test syntax
      run: |
        python -m py_compile main.py
        echo "✅ Syntax check passed"
        
    - name: Test quick build
      run: |
        pyinstaller --onefile --windowed --name="Syncra-Test" main.py
        
    - name: Verify build output
      run: |
        if (Test-Path "dist\Syncra-Test.exe") {
          Write-Host "✅ Test build successful"
          $size = (Get-Item "dist\Syncra-Test.exe").Length
          Write-Host "📦 File size: $([math]::Round($size/1MB, 2)) MB"
        } else {
          Write-Host "❌ Test build failed"
          exit 1
        }
      shell: powershell